services:
  redis:
    container_name: redis-dev
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  database:
    container_name: postgres
    image: postgres:15
    restart: always
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: baika_corporate

volumes:
  redis_data: null
  postgres_data: null
