export type ReadUserResponseDto = {
  id: number;
  role_id: number;
  communityId: number;
  street_id?: number | null;
  name: string;
  code?: string | null;
  phoneNumber: string;
  latitude?: number | null;
  longuitude?: number | null;
  email?: string | null;
  password: string;
  img?: string | null;
  Logged: boolean;
  created_At: string; 
  updated_At: string; 
  cpf: string;
  nationality: string;
  update_bi?: string | null; 
};